version: '3.8'

services:
  todo-app:
    image: ${IMAGE_NAME}
    container_name: todo-nodejs-app
    ports:
      - "4000:4000"
    environment:
      - mongoDbUrl=${MONGO_DB_URL}
    volumes:
      - todo-data:/app/data
    restart: unless-stopped

volumes:
  todo-data:
