version: '3.8'

services:
  todo-app:
    image: todo-nodejs-app:latest # ${IMAGE_NAME}
    container_name: todo-nodejs-app
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - todo-data:/app/data
    restart: unless-stopped

volumes:
  todo-data:
