version: '3.8'

services:
  todo-app:
    image: todo-nodejs-app  # The Docker image to use
    container_name: todo-nodejs-app  # Specifies a custom name for the container
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - todo-data:/app/data
    networks:
      - todo-network
    restart: unless-stopped

volumes:
  todo-data:

networks:
  todo-network:
    driver: bridge
