#============================================================================================
# Author: Amir ELbasiony
#-------------------------------------------------------------------------------------------
# Usage:
# Run the ansible playbook with the following command:
# ansible-playbook EC2_server.yaml
#-------------------------------------------------------------------------------------------
# Features:
# - Connects to private EC2 instances via SSM
# - Executes the playbook without requiring SSH keys or open ports
#============================================================================================
# ---
- name: Install Docker and Docker Compose via SSM on Private EC2
  hosts: private_ec2
  become: true

  roles:
    - docker_install
    - aws_cli_install