name: Deploy Infrastructure and Configure EC2s

on:
  push:
    branches: [main]
  workflow_dispatch:  # allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies (Ansible, pip, boto3, etc.)
      run: |
        sudo apt update
        sudo apt install -y ansible python3-pip graphviz
        pip3 install --upgrade pip
        pip3 install boto3 botocore amazon-ssm-helpers

    - name: Run infrastructure build and configure script
      working-directory: ./scripts
      run: |
        chmod +x ./infra_build_configure.sh
        ./infra_build_configure.sh
