name: Deploy Infrastructure and Configure EC2s

on:
  workflow_dispatch:  # manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Install Ansible collections
        run: ansible-galaxy collection install -r requirements.yml

      - name: Show installed Ansible collection versions
        run: ansible-galaxy collection list

      - name: Check amazon.aws version
        run: |
          ansible-galaxy collection list | grep amazon.aws || echo "amazon.aws not installed"
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz
                
      # - name: Run Ansible playbook
      #   run: |
      #     ansible-playbook Ansible_Rules/EC2_server.yaml -i Ansible_Rules/inventory.ini -vvv

      - name: Run infrastructure build and configure script
        working-directory: ./scripts
        run: |
          chmod +x ./infra_build_configure.sh
          ./infra_build_configure.sh
